# -*- coding: utf-8 -*-
"""KNN Regressor ML Prac Tae.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nPHaVGCK52IDQ0bzIyqOkI3sUSIqalTt
"""

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

df = pd.read_csv("hour.csv")
df = df.dropna()

print(df.head())
print(df.info())
print(df.shape)

X = df.drop(['cnt', 'dteday', 'instant', 'casual', 'registered'], axis=1)
y = df['cnt']

print("X shape:", X.shape)
print("y shape:", y.shape)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = KNeighborsRegressor(n_neighbors=5)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("MSE:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

plt.scatter(y_test, y_pred)
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.title("Actual vs Predicted - KNN")
plt.show()

errors = y_test - y_pred

plt.hist(errors, bins=20)
plt.title("Error Distribution - KNN")
plt.show()

plt.plot(y_test.values[:50], label="Actual")
plt.plot(y_pred[:50], label="Predicted")
plt.legend()
plt.title("Comparison - KNN")
plt.show()